version: "3"

services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - "9986:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bot
      MYSQL_USER: bot
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - /home/ahri/bot/mariadb:/var/lib/mysql
  discord-bot:
    depends_on:
      - mariadb
    image: discord-bot:1.8.0
    restart: always
    environment:
      MARIA_HOST_IP: mariadb
      TZ: Asia/Seoul
