version: "3"

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bot
      MYSQL_USER: bot
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - /home/ahri/bot/mariadb:/var/lib/mysql
    ports:
      - "9986:3306"
    networks:
      - bot
  discord-bot:
    image: discord-bot:1.8.5
    restart: always
    environment:
      TZ: Asia/Seoul
    depends_on:
      - mariadb
    links:
      - mariadb
    networks:
      - bot
networks:
  bot:
    driver: bridge